### ISSUE TITLE
Compilation on ARMv7

### ISSUE THREAD

**Issue by Teknoman117** [nickhutchinson/libdispatch#14]
Dunno if this is me or the project, but I can't get this working on ARMv7.  I've compiled libdispatch from this repository on a Beagleboard xM running debian 7.8 armhf build.  It *compiles* fine, but when I build the sample application and run it, it fails throwing an illegal hardware instruction error.  

I tried editing the CMakeLists.txt by adding -march=cortex-a8 and -mtune=cortex-a8, but it still fails to build correctly.  Tried compiling the sample both with gcc and clang, while dispatch was obviously compiled with clang.

 % clang -g -fblocks -ldispatch -o forever forever.c                            
 % gdb forever                                                           
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/nathaniel/Projects/dispatch/forever...done.
(gdb) run
Starting program: /home/nathaniel/Projects/dispatch/forever 
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb6e63bb0 (LWP 7841)]
[New Thread 0xb5e63bb0 (LWP 7843)]
[New Thread 0xb5663bb0 (LWP 7844)]
[New Thread 0xb6663bb0 (LWP 7842)]

Program received signal SIGILL, Illegal instruction.
0xb6f615a0 in syscall () from /lib/arm-linux-gnueabihf/libc.so.6
(gdb) bt
#0  0xb6f615a0 in syscall () from /lib/arm-linux-gnueabihf/libc.so.6
#1  0xb6fbe9b8 in pthread_main_np () at /home/nathaniel/build/libdispatch/src/shims/pthread_main_np.h:37
#2  dispatch_main () at /home/nathaniel/build/libdispatch/src/queue.c:2650
#3  0x000087d8 in main (argc=1, argv=0xbefff724) at forever.c:18
(gdb)

**Comment by Teknoman117** [comment]
Okay, so I tried tracking this down myself, and it seems that dispatch isn't the issue directly.  For some reason, the version of clang that is installed throws SIGILL when it executes syscall(SYS_gettid).

**Comment by Teknoman117** [comment]
So apparently this is happening because by default clang doesn't allow thumb instructions in the code by default AAAND the hand written assembly syscall function in eglibc has a thumb1 instruction in it.  Yay ... so if you add -mthumb to the CFLAGS of the build on ARM it compiles and functions correctly.
